name: mad_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ">=3.7.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8

    # ðŸ”¥ Firebase
    firebase_core: ^3.6.0
    firebase_auth: ^5.3.0

    # ðŸ” Social Login
    google_sign_in: ^6.2.3
    sign_in_with_apple: ^5.0.0
    flutter_web_auth_2: ^3.0.1

    # ðŸ–¼ Image Picker & Permissions
    image_picker: ^0.8.7+6
    permission_handler: ^12.0.1

    # ðŸ’¾ Persistence Packages
    shared_preferences: ^2.2.0
    path_provider: ^2.0.15

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/coffee_logo.png
        - assets/coffee_header.png

        # â˜• Coffee images
        - assets/coffee1.png
        - assets/coffee2.png
        - assets/coffee3.png
        - assets/coffee4.png
        - assets/coffee5.png
        - assets/coffee6.png
        - assets/coffee7.png
        - assets/coffee8.png
        - assets/coffee9.png
        - assets/coffee10.png
        - assets/coffee11.png
        - assets/coffee12.png
        - assets/coffee13.png
        - assets/coffee14.png

        # ðŸ–¼ Additional images
        - assets/img.png
        - assets/img_1.png
        - assets/img_2.png
        - assets/img_3.png
        - assets/img_4.png
        - assets/img_5.png
        - assets/img_6.png
        - assets/img_7.png
        - assets/img_8.png
        - assets/img_9.png
        - assets/img_10.png
        - assets/img_11.png
        - assets/img_12.png
        - assets/img_13.png
        - assets/img_14.png
        - assets/img_15.png
        - assets/img_16.png
        - assets/img_17.png
        - assets/img_18.png
        - assets/img_19.png
        - assets/img_20.png
        - assets/img_21.png
        - assets/img_22.png
        - assets/img_23.png
        - assets/img_24.png
        - assets/img_25.png
        - assets/img_26.png
        - assets/img_27.png
        - assets/img_28.png
        - assets/img_29.png
        - assets/img_30.png
        - assets/img_31.png
        - assets/img_32.png

        # ðŸ”¥ App branding
        - assets/logo.png
        - assets/bg.png

        # ðŸ” Social login icons
        - assets/img_33.png
        - assets/img_35.png
        - assets/img_36.png
